---
title: "About Page"
output:
  html_document:
  toc: true
  theme: united
---

# Motivation
    
Exposure to environmental chemicals is known to play a significant role in carcinogenesis. While some chemicals are well-known carcinogens, only a small fraction of those in commercial use and to which the human population is exposed has undergone thorough carcinogenicity testing.Furthermore, many of the biological mechanisms of actions of chemical carcinogens are poorly understood. The current gold standard for chemical carcinogenicity testing is the 2-year rat bioassay, which is expensive and time-consuming, and its relevance to human carcinogenesis has been questioned. To date, about ~1500 chemicals have been tested for long-term carcinogenicity in rodent models by this approach, out of the ~85,000 chemicals used in common household products or industrial settings. We aim to develop a fast and scalable approach to carcinogenicity screening, one that takes advantage of short-term chemical exposures in human cell lines and high-throughput gene expression profiling. This approach will support the profiling of a large number of chemicals in a rapid and cost-effective fashion, and will allow us to thoroughly evaluate the hypothesis that short-term in-vitro assays can accurately predict long-term in-vivo carcinogenicity.
                  
</br>

# Datasets

Currently, we have profiled two sets of chemicals in projects aimed at predicting liver and breast carcinogenicity, respectively. Our previous studies [Gusenleitner et al., 2014](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0102579) have shown that carcinogenicity prediction is exquisitely tissue-specific, and requires the fine tuning of the predictive model to the tissue being tested, hence the need for generating tissue-specific screens.  The first set of chemicals is composed of known liver carcinogens (according to evidence of tumor growth in rat livers according to the [CPDB](https://toxnet.nlm.nih.gov/cpdb/) and additional sources), non-carcinogens (known not to induce tumors in any sites in rats according to the CPDB), and other chemicals of interest to our collaborators in the Boston University Superfund Research Program. HEPG2 (human liver cancer) cell lines are exposed to each of the chemicals at 6 different doses for 24H. The second set of chemicals is composed of known or suspected breast carcinogens (according to the CPDB or [Rudel et. al., 2007](https://onlinelibrary.wiley.com/doi/10.1002/cncr.22653/pdf)), known lung carcinogens, non-carcinogens, or collaborator-selected chemicals. MCF10A (human non-transformed breast epithelial) cell lines as well as MCF10A with P53 knock-down, are exposed to each of the chemicals at 3 different doses for 24 hours and their gene expression profiled.

