---
output:
  flexdashboard::flex_dashboard:
    source_code: "https://github.com/montilab/Xposome/"
    orientation: rows
    vertical_layout: scroll
    theme: bootstrap
    css:
    - www/style.css
    - www/docsearch.css
    - www/bootstrap-toc.css
    includes:
      after_body: footer.Rhtml
---

```{r setup, include=FALSE}
library(rmarkdown)
library(shiny)

version= "0.0.1"

my_title <- paste0("<span><a class='navbar-link' href='#home'><strong>Xposome</strong></a>&ensp;<span class='version-label label-default' data-toggle='tooltip' data-placement='bottom' title='Released version'>", version, "</span></span>")
```

---
title: '`r htmltools::HTML(my_title)`'
---

<script type="text/javascript">
    $(document).ready(function() {
        document.title = "Xposome";
    });
</script>

Home {data-icon="fa-home"}
=====================================

```{r mainpage}
fluidRow(
  style="padding: 0 20px 20px 20px;",
  
  column(
    width=9,
    includeHTML("home/home.Rhtml")
  ),
  column(
    width=3, id="pkgdown-sidebar",
    includeHTML("links.Rhtml")
  )
)

observeEvent(input$docker-compose, {
  updateNavbarPage(session, inputId="docker-compose", selected="NGINX and Docker-Compose")
})

```

NGINX and Docker-Compose {data-icon="fa-plug"}
=====================================  

```{r docker-compose}

fluidRow(
  style="padding: 0 20px 20px 20px;",

  column(
    width=9,
    includeMarkdown("documentation/docker-compose.Rmd")
  ),
  column(
    width=3, id="pkgdown-sidebar",
    includeHTML("links.Rhtml")
  )
)

```

Send Emails with Postfix {data-icon="fa-envelope-square"}
=====================================  

```{r set-up postfix}

fluidRow(
  style="padding: 0 20px 20px 20px;",

  column(
    width=9,
    includeMarkdown("documentation/postfix.Rmd")
  ),
  column(
    width=3, id="pkgdown-sidebar",
    includeHTML("links.Rhtml")
  )
)

```

API Explorer {data-icon="fa-link"}
=====================================

```{r api}

fluidRow(
  style="padding: 0 20px 20px 20px;",

  column(
    width=9,
    includeMarkdown("api/api.Rmd")
  ),
  column(
    width=3, id="pkgdown-sidebar",
    includeHTML("links.Rhtml")
  )
)
```






